// <auto-generated />
using System;
using AdvancedForms.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdvancedForms.Migrations.Npgsql
{
    [DbContext(typeof(NpgsqlFormContext))]
    partial class NpgsqlFormContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdvancedForms.Models.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UseCodes")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("AdvancedForms.Models.Preset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Presets");
                });

            modelBuilder.Entity("AdvancedForms.Models.PresetTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PresetTemplate");
                });

            modelBuilder.Entity("AdvancedForms.Models.PresetTemplateValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("PresetTemplateValue");
                });

            modelBuilder.Entity("AdvancedForms.Models.PresetValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PresetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PresetId");

                    b.ToTable("PresetValue");
                });

            modelBuilder.Entity("AdvancedForms.Models.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FormId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PresetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("PresetId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("AdvancedForms.Models.ResponseValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResponseId");

                    b.ToTable("ResponseValue");
                });

            modelBuilder.Entity("AdvancedForms.Models.Preset", b =>
                {
                    b.HasOne("AdvancedForms.Models.Form", "Form")
                        .WithMany("Presets")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdvancedForms.Models.PresetTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId");

                    b.Navigation("Form");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("AdvancedForms.Models.PresetTemplateValue", b =>
                {
                    b.HasOne("AdvancedForms.Models.PresetTemplate", "Template")
                        .WithMany("Values")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("AdvancedForms.Models.PresetValue", b =>
                {
                    b.HasOne("AdvancedForms.Models.Preset", "Preset")
                        .WithMany("Values")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("AdvancedForms.Models.Response", b =>
                {
                    b.HasOne("AdvancedForms.Models.Form", null)
                        .WithMany("Responses")
                        .HasForeignKey("FormId");

                    b.HasOne("AdvancedForms.Models.Preset", "Preset")
                        .WithMany("Responses")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("AdvancedForms.Models.ResponseValue", b =>
                {
                    b.HasOne("AdvancedForms.Models.Response", "Response")
                        .WithMany("Values")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Response");
                });

            modelBuilder.Entity("AdvancedForms.Models.Form", b =>
                {
                    b.Navigation("Presets");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("AdvancedForms.Models.Preset", b =>
                {
                    b.Navigation("Responses");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("AdvancedForms.Models.PresetTemplate", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("AdvancedForms.Models.Response", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
